### ISSUE TITLE
No change in my Audience list

### ISSUE THREAD

**Issue by Jean-PhilippeDESCAMPS** [mailchimp/Mailchimp-SDK-iOS#17]
Hello, 

I just integrate your framework in my app.
``` swift
static func updateSubscriber(email: String!, firstname: String!, lastname: String!, compagny: String!) {
        do {
            try MailchimpSDK.initialize(token: KEY, autoTagContacts: true, debugMode: true)
            var contact: Contact = Contact(emailAddress: email)
            let mergeFields = ["FNAME": MergeFieldValue.string(firstname),
                               "LNAME": MergeFieldValue.string(lastname)]
            contact.mergeFields = mergeFields
            contact.tags = [Contact.Tag(name: compagny, status: .active)]
            MailchimpSDK.createOrUpdate(contact: contact) { result in
                switch result {
                case .success:
                    print("Successfully added or updated contact")
                case .failure(let error):
                    print("Error: \(error.localizedDescription)")
                }
            }
        } catch {
            
        }
    }
```

When I launch my app and call my method I got a result success :
```
Mailchimp SDK Initialized. Version: 0.1.1
Adding auto-tag "iOS" to create contact request.
Adding auto-tag "Phone" to create contact request.
Successfully added or updated contact
```

When I go on my Mailchimp account I didn't see my contact updated with name and last name or a new tag.

I create an Api Key to give as Token to the SDK.
I don't know why it's not working even I get a result successful.

Best
Jean-Philippe

**Comment by michael-heard-mc** [comment]
Hi @Jean-PhilippeDESCAMPS, were you able to resolve this issue? If not, can you double-check that you are using the correct SDK key?

**Comment by Jean-PhilippeDESCAMPS** [comment]
@michael-heard-mc How can I generate my SDK key, the readme no mention that. Its written "coming soon" ?

**Comment by michael-heard-mc** [comment]
@Jean-PhilippeDESCAMPS Currently the SDK is in a private beta but we'd love for you to try it out. Can you email mobilesdk@mailchimp.com with your Mailchimp username? We can then get your account set up for it.

**Comment by Jean-PhilippeDESCAMPS** [comment]
I send you an email. 
Thanks a lot.
