### ISSUE TITLE
Can not archive my app with Mailchimp framework

### ISSUE THREAD

**Issue by Jean-PhilippeDESCAMPS** [mailchimp/Mailchimp-SDK-iOS#22]
Hi,

I can't archive my project with the sdk embed and sign.
it says that 'MailchimpSDK' is unavailable: cannot find Swift declaration for this class

Do you need more info ?
Best 
Jean-Philippe

**Comment by jennifer-starratt** [comment]
Hi @Jean-PhilippeDESCAMPS, can you confirm what version of Xcode you are using, your supported iOS versions, what your project's "Valid Architectures" is set to and if your project is Obj-C/Swift/both? Also, do you have `import MailchimpSDK` at the top of the relevant files?

**Comment by Jean-PhilippeDESCAMPS** [comment]
Hi @jennifer-starratt 

Im using Xcode 11.3.1 with a swift project.
I can push my app from Xcode directly on my iPhone XR and iPhone 5S.
My apps is iOS 10+

![Capture d’écran 2020-02-24 à 17 36 18](https://user-images.githubusercontent.com/427766/75171624-37871a80-572c-11ea-814b-72be35c0a516.png)

**Comment by jennifer-starratt** [comment]
> Hi @jennifer-starratt
> 
> Im using Xcode 11.3.1 with a swift project.
> I can push my app from Xcode directly on my iPhone XR and iPhone 5S.
> My apps is iOS 10+

Thank you for the quick reply. The SDK requires a deployment target of iOS 11+. Would it be possible to adjust that setting and test again?

**Comment by jennifer-starratt** [comment]
> Hi @jennifer-starratt
> 
> Im using Xcode 11.3.1 with a swift project.
> I can push my app from Xcode directly on my iPhone XR and iPhone 5S.
> My apps is iOS 10+

@Jean-PhilippeDESCAMPS Thank you for the quick reply. The SDK requires a deployment target of iOS 11+. Would it be possible to adjust that setting and test again?

**Comment by Jean-PhilippeDESCAMPS** [comment]
its works thank you !
