### ISSUE TITLE
Unable to add/Update contact with SWIFT SDK in iOS

### ISSUE THREAD

**Issue by harshhsharma2007** [mailchimp/Mailchimp-SDK-iOS#32]
Hi Support, 

**API Key:** <Redacted>
**Username:** <Redacted>

I am getting a success message after adding/update contact with your SDK but it's not reflecting on the mailchimp dashboard. I am using Swift SDK for my iOS app. 
Code for mailchimp SDK initialisation:
```swift
do {
    try MailchimpSDK.initialize(token: "<Redacted>", autoTagContacts: true, debugMode: true)
} catch MailchimpSDK.InitError.invalidToken {
}
```

Adding/Update Contact:
```swift
var contact: Contact = Contact(emailAddress: "harshhsharma2007@gmail.com")
let mergeFields = ["FNAME": MergeFieldValue.string("Example"), "LNAME": MergeFieldValue.string("User")]
contact.mergeFields = mergeFields
MailchimpSDK.createOrUpdate(contact: contact) { result in
    switch result {
    case .success:
        print("Successfully added or updated contact")
    case .failure(let error):
        print("Error: \(error.localizedDescription)")
    }
}
```

SDK We are using:https://github.com/mailchimp/Mailchimp-SDK-iOS

**Comment by michael-heard-mc** [comment]
Hey, thanks for reaching out. We're not seeing any issues with the code you provided and looking in your account it seems the email in your code example is in your Audience and added from the SDK. Can you send us a screenshot of the dashboard you're not seeing update? And what you expect to appear there? You can email those details to mobile-sdk@mailchimp.com

Also a warning, posting your SDK key and username is not advised on a public forum like this. We went ahead and redacted it from your original message but it could still be found. We'd advise disabling that key and using another. You can disable the key from the API Keys page. This guide explains getting to that page: https://mailchimp.com/help/mobile-sdk/#Generate_an_SDK_Key
