### ISSUE TITLE
Adding user to contact list is failing

### ISSUE THREAD

**Issue by gbesler** [mailchimp/Mailchimp-SDK-iOS#38]
I can successfully initialize Mailchimp in debug mode and I am trying to create a contact from my app. But I receive an error:

Error: The operation couldn’t be completed. (appname.APIError error 4.)

What I do is:

     var contact: Contact = Contact(emailAddress: "some@email.com")
            
            let emailPermission = Contact.MarketingPermission(marketingPermissionId: "emailPermissinon", enabled: true)
            let mailPermission = Contact.MarketingPermission(marketingPermissionId: "mailPermission", enabled: true)
            let adPermission = Contact.MarketingPermission(marketingPermissionId: "adPermission", enabled: true)

            contact.marketingPermissions = [emailPermission, mailPermission, adPermission]
            MailchimpSDK.createOrUpdate(contact: contact) { result in
                switch result {
                case .success:
                    print("Successfully added or updated contact")
                case .failure(let error):
                    print("Error: \(error.localizedDescription)")
                }
            }

What am I doing wrong?

**Comment by michael-patzer** [comment]
Hi @gbesler. Thanks for opening the issue and providing a code sample.

Case 4 in the `APIError` enum is `apiError(response: APIErrorResponse)`. Could you print out the `status`, `type`, and `detail` of the `APIErrorResponse`?

```
        MailchimpSDK.createOrUpdate(contact: contact) { result in
            switch result {
            case .success:
                print("Successfully added or updated contact")
            case .failure(let error):
                print("Error: \(error.localizedDescription)")
                switch error {
                case .apiError(response: APIErrorResponse)
                    print("Status: \(response.status), Type: \(response.type), Detail: \(response.detail)")
                }
            }
        }
```

**Comment by gbesler** [comment]
Hi @michael-patzer 
I have tried what you have written but it is not going under .apiError. What I get is an invalidUrl error. Please check this:

<img width="537" alt="Screen Shot 2020-07-23 at 22 47 07" src="https://user-images.githubusercontent.com/6095238/88335913-bfee0380-cd3c-11ea-862d-c25a592a74d1.png">

**Comment by michael-patzer** [comment]
@gbesler Thank you. We'll take a look at this. You may also contribute a fix if you'd like. When you open a PR, the `cla-bot` will give instructions on how to sign our Contributor License Agreement.
