### ISSUE TITLE
Mailchimp SDK not integrating

### ISSUE THREAD

**Issue by denver91** [mailchimp/Mailchimp-SDK-iOS#39]
Dear Mailchimp developers,

I am trying to integrate Mailchimp SDK to my social media app by installing with cocoapods but it returns an error.

<img width="895" alt="problem" src="https://user-images.githubusercontent.com/68713183/88341965-3263e100-cd47-11ea-863b-201e5c44eb51.png">

I tried it in a clean project and also in another Macbook. No luck. It returns the same error and cannot find the framework.
I also followed your guide to install it manually with XCFramework and still the same error. 

To be sure it is not problem on my side, I tried many other new pods to check if they will fail... No, they all work fine.

I hope you can let me know what is the problem here.

**Comment by michael-patzer** [comment]
@denver91 Thanks for opening this issue. Can you provide me with more information to help me troubleshoot the issue?

- What version of Xcode are you running?
- What's your iOS Deployment Target? `Deployment Info > Target > iOS version`
- Are you opening the `.xcworkspace` rather than the `.xcodeproj`?
- Can you post the contents of your `Podfile`? Please redact any private information.

**Comment by denver91** [comment]
- My deployment target is iOS 12. Xcode version is 11.5.
- Yes I tried .xcworkspace
- I tried on clean swift project as well as my own project. So there is only MailchimpSDK pod in my pod file. So it is not related to my podfile.
- I did pod deintegrate but it did not work. As I told, I tried other new pods that I did not added before to see if it is my problem but it is not.

**Comment by michael-patzer** [comment]
Hi @denver91,

I'm not certain this will help, but I updated our Podspec to the latest (v1.0) on https://cocoapods.org/pods/MailchimpSDK

To test Cocoapods integration, I created a new blank Swift project on Xcode 11.6, with a deployment target of iOS 12. Here is my `Podfile`:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntegrateMailchimpSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntegrateMailchimpSDK
  pod 'MailchimpSDK'

end
```

Installation was successful:
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing MailchimpSDK (1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `IntegrateMailchimpSDK.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

Building was also successful:
![Screen Shot 2020-07-28 at 2 31 30 PM](https://user-images.githubusercontent.com/42217691/88706702-32653780-d0df-11ea-8012-bd4bca83eeb7.png)

Can you let me know if running `pod install --repo-update` solves your issue? If not, could you upload a `.zip` of the clean Swift project you created that is causing the `framework not found` error above?

Sorry for the frustration. I'll do my best to help you troubleshoot. We appreciate you being an early adopter.

**Comment by viraj** [comment]
Hi I had the same issue as @denver91 
- My deployment target is iOS 13. Xcode version is 12.0
- # platform :ios, '13.0'

Tried @michael-patzer solution as well but no luck.
So I tried with SPM - [https://github.com/mailchimp/Mailchimp-SDK-iOS#option-3-swift-package-manager](Option 3)
