### ISSUE TITLE
[BUG] This person is only eligible for transactional emails

### ISSUE THREAD

**Issue by jkandzi** [mailchimp/Mailchimp-SDK-iOS#47]
**Describe the bug**
I'm seeing "This person is only eligible for transactional emails" for contacts signed up from the iOS sdk, even though i copy pasted the permissions from the client key website and set `enabled` to `true` on all of them:

```
//Email Marketing Permission
let permissiondXXX = Contact.MarketingPermission(marketingPermissionId: "XXX", enabled: true)
//Direct Mail Marketing Permission
let permissionXXX = Contact.MarketingPermission(marketingPermissionId: "XXX", enabled: true)
//Customized Online Advertising Marketing Permission
let permissionXXX = Contact.MarketingPermission(marketingPermissionId: "XXX", enabled: true)
contact.marketingPermissions = [permissiondXXX, permissionXXX, permissionXXX]
```

Is there something else i have to do if i want to signup users to newsletters from an ios app?

**Expected behavior**
The user should be able to receive newsletters.

**Development Environment Information:**
 - Xcode Version: 12.0.1
 - iOS Deployment Target (Deployment Info > Target > iOS version): iOS 12.4
 - Mailchimp SDK Version: 2.0.6

**Comment by jennifer-starratt** [comment]
Hi @jkandzi. Thanks for opening an issue and providing a code sample.

To enable marketing campaigns for a contact, you will also need to set the contact status as `subscribed`:

```
contact.status = .subscribed
```

Do you have that as well?

**Comment by jkandzi** [comment]
i missed that, thanks for the quick response 🙏
