### ISSUE TITLE
[BUG] not relevant APIErrorResponse and strange behaviour

### ISSUE THREAD

**Issue by japanese-goblinn** [mailchimp/Mailchimp-SDK-iOS#62]
**Describe the bug**
API returns a unrelevant error for some emails, i.e. email "lol@lol.lol" successfully created (screenshot_0) but "lol@lol.com" is not (screenshot_1) and it's returning strange error (screenshot_2). If it's some internal validation of emails I thinks it's better to provide more useful descriptions of what went wrong as well as adding more meaningful status code. Thanks 

**Screenshots**

<img width="576" alt="image" src="https://user-images.githubusercontent.com/33631005/107992494-e54ca280-6fe9-11eb-8489-3c47369dc6a6.png">

<img width="545" alt="Screenshot 2021-02-16 at 00 01 46" src="https://user-images.githubusercontent.com/33631005/107992640-2b096b00-6fea-11eb-962a-7feddf7574eb.png">

<img width="285" alt="Screenshot 2021-02-16 at 00 00 05" src="https://user-images.githubusercontent.com/33631005/107992510-ee3d7400-6fe9-11eb-991a-10bb0daab6a2.png">

**Development Environment Information:**
 - Xcode Version: 12.4
 - iOS Deployment Target (Deployment Info > Target > iOS version): iOS 11.4
 - Mailchimp SDK Version: 2.0.2

**Comment by michael-patzer** [comment]
@japanese-goblinn Thanks for the descriptive report and screenshots. It appears that this SDK client code is responding properly with an error, but the error from our backend isn't particularly descriptive.

I'll speak with some of our API engineers and see if we can provide more detail on these error responses, or at least explain why we return generic responses.

**Comment by japanese-goblinn** [comment]
Yep, that would be very nice

**Comment by michael-patzer** [comment]
@japanese-goblinn I merged https://github.com/mailchimp/Mailchimp-SDK-iOS/pull/63 to display better error logs. The particular e-mail address in question returns: `This email address is invalid.` in the logs. This should be rare and just happens to affect the e-mail address used in your example.

If you have any issues subscribing your real customers to your list with the SDK (i.e. encountering this error), you can reach out to Mailchimp Customer Support from within your Mailchimp.com account and they can resolve any issues that may be specific to either your account or your customers.

Thanks for bringing this issue up.
