### ISSUE TITLE
[Question] What is the max length of Event Property String value?

### ISSUE THREAD

**Issue by jtm57** [mailchimp/Mailchimp-SDK-iOS#70]
### Feature question

**Feature**
Event Property

**Question**
What is max length of Event Property String value?

---

**Comment by chelsea-youmans** [comment]
@jtm57 Hello! Event names must be 2-30 characters. The Marketing API documentation has info on an equivalent endpoint here: https://mailchimp.com/developer/marketing/api/list-member-events/add-event/

I hope that helps!

**Comment by chelsea-youmans** [comment]
Ah, sorry about that. I am unaware of a character limit on event property keys or values.

**Comment by jtm57** [comment]
Thanks, @chelsea-youmans .
