### ISSUE TITLE
[BUG] Xcode 16 bitcode enabled

### ISSUE THREAD

**Issue by MurphyHBrantley** [mailchimp/Mailchimp-SDK-iOS#77]
Using Xcode 16 with the most recent MailchimpSDK installed via cocoapods, attempting to distribute an archived iPad gives an error:

Asset Validation Failed
Invalid Executable. The executable 'MyApp.app/Frameworks/MailchimpSDK.framework/MailchimpSDK' contains bitcode

Can the MailchimpSDK be updated to remove bitcode for Xcode 16 support?

**Comment by joe-schofield** [comment]
@MurphyHBrantley Are you able to try using [SPM](https://github.com/mailchimp/Mailchimp-SDK-iOS#option-3-swift-package-manager) instead of cocoapods to see if this resolves your issue?

**Comment by MurphyHBrantley** [comment]
@joe-schofield Using SPM did resolve the issue, thanks!

**Comment by MateuszW13** [comment]
Hi, are there any plans to fix it for CocoaPods?

**Comment by BAndonovski** [comment]
This is still not fixed for CocoaPods

**Comment by MurphyHBrantley** [comment]
@MateuszW13 @BAndonovski It works if you install using SPM. 

Here was my setup:
location: https://github.com/mailchimp/Mailchimp-SDK-iOS#option-3-swift-package-manager
dependency rule: Branch - main

**Comment by BAndonovski** [comment]
@MurphyHBrantley  That might be true, but it does not work with CocoaPods.
